server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food_ordering_system
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ngoquangtruongx4@gmail.com  # Gmail gửi đi
    password: teyh srrf nuqo phgk   # App Password Gmail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 15000
          timeout: 15000
          writetimeout: 15000
  #          gioi han anh
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
jwt:
  secret: examSecretKeyexamSecretKeyexamSecretKey123456789
  access-expiration: 1800000
  refresh-expiration: 604800000


sepay:
  bank-account: 18995736789
  bank-name: TPBank

app:
  backend-url: http://localhost:8080
# backend-url: https://subfractionally-wrinkleable-kenneth.ngrok-free.dev de hien qr public
  frontend-url: http://localhost:5173